#! /usr/bin/env python

import sys
import getopt
from elfesteem import ELF


def usage():
    print >>sys.stderr,"Usage: elfcli [-i inputfile]"
    raise SystemExit

def main(*args):
    INPUT=sys.stdin
    try:
        opts = getopt.getopt(args,"hi:")
        for opt,optarg in opts[0]:
            if opt == "-h":
                usage()
            if opt == "-i":
                INPUT = open(optarg)
    except getopt.GetoptError,e:
        print >>sys.stderr,"ERROR: %s" % e
        raise SystemExit
    

if __name__ == "__main__":
    main(*sys.argv[1:])
