#! /usr/bin/env python

import sys
import code
#import elfesteem.elf
import readline
import argparse



def usage():
    print >>sys.stderr,"Usage: elfcli [-i inputfile]"
    raise SystemExit

def main():
    
    parser = argparse.ArgumentParser()
    parser.add_argument("infile")

    options = parser.parse_args()

    # prepare locals and binding for interactive session
    readline.parse_and_bind("tab: complete")
    del(parser)
    from elfesteem import *
    
    elf = elf_init.ELF(open(options.infile).read())
    
    code.interact(local=locals())
    

if __name__ == "__main__":
    main()
