#! /usr/bin/env python

tests = [

# Non-regression tests from wine
("??0bad_alloc@std@@QAE@ABV01@@Z", "public: __thiscall std::bad_alloc::bad_alloc(class std::bad_alloc const &)"),
("??0bad_alloc@std@@QAE@PBD@Z", "public: __thiscall std::bad_alloc::bad_alloc(char const *)"),
("??0bad_cast@@AAE@PBQBD@Z", "private: __thiscall bad_cast::bad_cast(char const * const *)"),
("??0bad_cast@@QAE@ABQBD@Z", "public: __thiscall bad_cast::bad_cast(char const * const &)"),
("??0bad_cast@@QAE@ABV0@@Z", "public: __thiscall bad_cast::bad_cast(class bad_cast const &)"),
("??0bad_exception@std@@QAE@ABV01@@Z", "public: __thiscall std::bad_exception::bad_exception(class std::bad_exception const &)"),
("??0bad_exception@std@@QAE@PBD@Z", "public: __thiscall std::bad_exception::bad_exception(char const *)"),
("??0?$basic_filebuf@DU?$char_traits@D@std@@@std@@QAE@ABV01@@Z", "public: __thiscall std::basic_filebuf<char,struct std::char_traits<char>>::basic_filebuf<char,struct std::char_traits<char>>(class std::basic_filebuf<char,struct std::char_traits<char>> const &)"),
("??0?$basic_filebuf@DU?$char_traits@D@std@@@std@@QAE@PAU_iobuf@@@Z", "public: __thiscall std::basic_filebuf<char,struct std::char_traits<char>>::basic_filebuf<char,struct std::char_traits<char>>(struct _iobuf *)"),
("??0?$basic_filebuf@DU?$char_traits@D@std@@@std@@QAE@W4_Uninitialized@1@@Z", "public: __thiscall std::basic_filebuf<char,struct std::char_traits<char>>::basic_filebuf<char,struct std::char_traits<char>>(enum std::_Uninitialized)"),
("??0?$basic_filebuf@GU?$char_traits@G@std@@@std@@QAE@ABV01@@Z", "public: __thiscall std::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>(class std::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>> const &)"),
("??0?$basic_filebuf@GU?$char_traits@G@std@@@std@@QAE@PAU_iobuf@@@Z", "public: __thiscall std::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>(struct _iobuf *)"),
("??0?$basic_filebuf@GU?$char_traits@G@std@@@std@@QAE@W4_Uninitialized@1@@Z", "public: __thiscall std::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>(enum std::_Uninitialized)"),
("??0?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@ABV01@@Z", "public: __thiscall std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>(class std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("??0?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@H@Z", "public: __thiscall std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &,int)"),
("??0?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@H@Z", "public: __thiscall std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>(int)"),
("??0?$basic_stringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@ABV01@@Z", "public: __thiscall std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>(class std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("??0?$basic_stringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@1@H@Z", "public: __thiscall std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &,int)"),
("??0?$basic_stringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAE@H@Z", "public: __thiscall std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>(int)"),
("??0?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@QAE@ABV_Locinfo@1@I@Z", "public: __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>(class std::_Locinfo const &,unsigned int)"),
("??0?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@QAE@I@Z", "public: __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>(unsigned int)"),
("??0?$num_get@GV?$istreambuf_iterator@GU?$char_traits@G@std@@@std@@@std@@QAE@ABV_Locinfo@1@I@Z", "public: __thiscall std::num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>::num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>(class std::_Locinfo const &,unsigned int)"),
("??0?$num_get@GV?$istreambuf_iterator@GU?$char_traits@G@std@@@std@@@std@@QAE@I@Z", "public: __thiscall std::num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>::num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>(unsigned int)"),
("??0streambuf@@QAE@ABV0@@Z", "public: __thiscall streambuf::streambuf(class streambuf const &)"),
("??0strstreambuf@@QAE@ABV0@@Z", "public: __thiscall strstreambuf::strstreambuf(class strstreambuf const &)"),
("??0strstreambuf@@QAE@H@Z", "public: __thiscall strstreambuf::strstreambuf(int)"),
("??0strstreambuf@@QAE@P6APAXJ@ZP6AXPAX@Z@Z", "public: __thiscall strstreambuf::strstreambuf(void * (__cdecl *)(long),void (__cdecl *)(void *))"),
("??0strstreambuf@@QAE@PADH0@Z", "public: __thiscall strstreambuf::strstreambuf(char *,int,char *)"),
("??0strstreambuf@@QAE@PAEH0@Z", "public: __thiscall strstreambuf::strstreambuf(unsigned char *,int,unsigned char *)"),
("??0strstreambuf@@QAE@XZ", "public: __thiscall strstreambuf::strstreambuf(void)"),
("??1__non_rtti_object@std@@UAE@XZ", "public: virtual __thiscall std::__non_rtti_object::~__non_rtti_object(void)"),
("??1__non_rtti_object@@UAE@XZ", "public: virtual __thiscall __non_rtti_object::~__non_rtti_object(void)"),
("??1?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@UAE@XZ", "public: virtual __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::~num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>(void)"),
("??1?$num_get@GV?$istreambuf_iterator@GU?$char_traits@G@std@@@std@@@std@@UAE@XZ", "public: virtual __thiscall std::num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>::~num_get<unsigned short,class std::istreambuf_iterator<unsigned short,struct std::char_traits<unsigned short>>>(void)"),
("??4istream_withassign@@QAEAAV0@ABV0@@Z", "public: class istream_withassign & __thiscall istream_withassign::operator=(class istream_withassign const &)"),
("??4istream_withassign@@QAEAAVistream@@ABV1@@Z", "public: class istream & __thiscall istream_withassign::operator=(class istream const &)"),
("??4istream_withassign@@QAEAAVistream@@PAVstreambuf@@@Z", "public: class istream & __thiscall istream_withassign::operator=(class streambuf *)"),
("??5std@@YAAAV?$basic_istream@DU?$char_traits@D@std@@@0@AAV10@AAC@Z", "class std::basic_istream<char,struct std::char_traits<char>> & __cdecl std::operator>>(class std::basic_istream<char,struct std::char_traits<char>> &,signed char &)"),
("??5std@@YAAAV?$basic_istream@DU?$char_traits@D@std@@@0@AAV10@AAD@Z", "class std::basic_istream<char,struct std::char_traits<char>> & __cdecl std::operator>>(class std::basic_istream<char,struct std::char_traits<char>> &,char &)"),
("??5std@@YAAAV?$basic_istream@DU?$char_traits@D@std@@@0@AAV10@AAE@Z", "class std::basic_istream<char,struct std::char_traits<char>> & __cdecl std::operator>>(class std::basic_istream<char,struct std::char_traits<char>> &,unsigned char &)"),
("??6?$basic_ostream@GU?$char_traits@G@std@@@std@@QAEAAV01@P6AAAVios_base@1@AAV21@@Z@Z", "public: class std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>> & __thiscall std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>>::operator<<(class std::ios_base & (__cdecl *)(class std::ios_base &))"),
("??6?$basic_ostream@GU?$char_traits@G@std@@@std@@QAEAAV01@PAV?$basic_streambuf@GU?$char_traits@G@std@@@1@@Z", "public: class std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>> & __thiscall std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>>::operator<<(class std::basic_streambuf<unsigned short,struct std::char_traits<unsigned short>> *)"),
("??6?$basic_ostream@GU?$char_traits@G@std@@@std@@QAEAAV01@PBX@Z", "public: class std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>> & __thiscall std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>>::operator<<(void const *)"),
("??_8?$basic_fstream@DU?$char_traits@D@std@@@std@@7B?$basic_ostream@DU?$char_traits@D@std@@@1@@", "const std::basic_fstream<char,struct std::char_traits<char>>::`vbtable'{for `std::basic_ostream<char,struct std::char_traits<char>>'}"),
("??_8?$basic_fstream@GU?$char_traits@G@std@@@std@@7B?$basic_istream@GU?$char_traits@G@std@@@1@@", "const std::basic_fstream<unsigned short,struct std::char_traits<unsigned short>>::`vbtable'{for `std::basic_istream<unsigned short,struct std::char_traits<unsigned short>>'}"),
("??_8?$basic_fstream@GU?$char_traits@G@std@@@std@@7B?$basic_ostream@GU?$char_traits@G@std@@@1@@", "const std::basic_fstream<unsigned short,struct std::char_traits<unsigned short>>::`vbtable'{for `std::basic_ostream<unsigned short,struct std::char_traits<unsigned short>>'}"),
("??9std@@YA_NPBDABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@@Z", "bool __cdecl std::operator!=(char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("??9std@@YA_NPBGABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@0@@Z", "bool __cdecl std::operator!=(unsigned short const *,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("??A?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEAADI@Z", "public: char & __thiscall std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>>::operator[](unsigned int)"),
("??A?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEABDI@Z", "public: char const & __thiscall std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>>::operator[](unsigned int)const"),
("??A?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEAAGI@Z", "public: unsigned short & __thiscall std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::operator[](unsigned int)"),
("??A?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBEABGI@Z", "public: unsigned short const & __thiscall std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::operator[](unsigned int)const"),
("?abs@std@@YAMABV?$complex@M@1@@Z", "float __cdecl std::abs(class std::complex<float> const &)"),
("?abs@std@@YANABV?$complex@N@1@@Z", "double __cdecl std::abs(class std::complex<double> const &)"),
("?abs@std@@YAOABV?$complex@O@1@@Z", "long double __cdecl std::abs(class std::complex<long double> const &)"),
("?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A", "class std::basic_istream<char,struct std::char_traits<char>> std::cin"),
("?do_get@?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MBE?AV?$istreambuf_iterator@DU?$char_traits@D@std@@@2@V32@0AAVios_base@2@AAHAAG@Z", "protected: virtual class std::istreambuf_iterator<char,struct std::char_traits<char>> __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::do_get(class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::ios_base &,int &,unsigned short &)const"),
("?do_get@?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MBE?AV?$istreambuf_iterator@DU?$char_traits@D@std@@@2@V32@0AAVios_base@2@AAHAAI@Z", "protected: virtual class std::istreambuf_iterator<char,struct std::char_traits<char>> __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::do_get(class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::ios_base &,int &,unsigned int &)const"),
("?do_get@?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MBE?AV?$istreambuf_iterator@DU?$char_traits@D@std@@@2@V32@0AAVios_base@2@AAHAAJ@Z", "protected: virtual class std::istreambuf_iterator<char,struct std::char_traits<char>> __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::do_get(class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::ios_base &,int &,long &)const"),
("?do_get@?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MBE?AV?$istreambuf_iterator@DU?$char_traits@D@std@@@2@V32@0AAVios_base@2@AAHAAK@Z", "protected: virtual class std::istreambuf_iterator<char,struct std::char_traits<char>> __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::do_get(class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::ios_base &,int &,unsigned long &)const"),
("?do_get@?$num_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@MBE?AV?$istreambuf_iterator@DU?$char_traits@D@std@@@2@V32@0AAVios_base@2@AAHAAM@Z", "protected: virtual class std::istreambuf_iterator<char,struct std::char_traits<char>> __thiscall std::num_get<char,class std::istreambuf_iterator<char,struct std::char_traits<char>>>::do_get(class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::istreambuf_iterator<char,struct std::char_traits<char>>,class std::ios_base &,int &,float &)const"),
("?_query_new_handler@@YAP6AHI@ZXZ", "int (__cdecl * __cdecl _query_new_handler(void))(unsigned int)"),
("?register_callback@ios_base@std@@QAEXP6AXW4event@12@AAV12@H@ZH@Z", "public: void __thiscall std::ios_base::register_callback(void (__cdecl *)(enum std::ios_base::event,class std::ios_base &,int),int)"),
("?seekg@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEAAV12@JW4seekdir@ios_base@2@@Z", "public: class std::basic_istream<char,struct std::char_traits<char>> & __thiscall std::basic_istream<char,struct std::char_traits<char>>::seekg(long,enum std::ios_base::seekdir)"),
("?seekg@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEAAV12@V?$fpos@H@2@@Z", "public: class std::basic_istream<char,struct std::char_traits<char>> & __thiscall std::basic_istream<char,struct std::char_traits<char>>::seekg(class std::fpos<int>)"),
("?seekg@?$basic_istream@GU?$char_traits@G@std@@@std@@QAEAAV12@JW4seekdir@ios_base@2@@Z", "public: class std::basic_istream<unsigned short,struct std::char_traits<unsigned short>> & __thiscall std::basic_istream<unsigned short,struct std::char_traits<unsigned short>>::seekg(long,enum std::ios_base::seekdir)"),
("?seekg@?$basic_istream@GU?$char_traits@G@std@@@std@@QAEAAV12@V?$fpos@H@2@@Z", "public: class std::basic_istream<unsigned short,struct std::char_traits<unsigned short>> & __thiscall std::basic_istream<unsigned short,struct std::char_traits<unsigned short>>::seekg(class std::fpos<int>)"),
("?seekoff@?$basic_filebuf@DU?$char_traits@D@std@@@std@@MAE?AV?$fpos@H@2@JW4seekdir@ios_base@2@H@Z", "protected: virtual class std::fpos<int> __thiscall std::basic_filebuf<char,struct std::char_traits<char>>::seekoff(long,enum std::ios_base::seekdir,int)"),
("?seekoff@?$basic_filebuf@GU?$char_traits@G@std@@@std@@MAE?AV?$fpos@H@2@JW4seekdir@ios_base@2@H@Z", "protected: virtual class std::fpos<int> __thiscall std::basic_filebuf<unsigned short,struct std::char_traits<unsigned short>>::seekoff(long,enum std::ios_base::seekdir,int)"),
("?set_new_handler@@YAP6AXXZP6AXXZ@Z", "void (__cdecl * __cdecl set_new_handler(void (__cdecl *)(void)))(void)"),
("?str@?$basic_istringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z", "public: void __thiscall std::basic_istringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("?str@?$basic_istringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ", "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> __thiscall std::basic_istringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(void)const"),
("?str@?$basic_istringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEXABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z", "public: void __thiscall std::basic_istringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("?str@?$basic_istringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBE?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@XZ", "public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> __thiscall std::basic_istringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(void)const"),
("?str@?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z", "public: void __thiscall std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("?str@?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ", "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> __thiscall std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(void)const"),
("?str@?$basic_ostringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEXABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z", "public: void __thiscall std::basic_ostringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("?str@?$basic_ostringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBE?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@XZ", "public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> __thiscall std::basic_ostringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(void)const"),
("?str@?$basic_stringbuf@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z", "public: void __thiscall std::basic_stringbuf<char,struct std::char_traits<char>,class std::allocator<char>>::str(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("?str@?$basic_stringbuf@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ", "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> __thiscall std::basic_stringbuf<char,struct std::char_traits<char>,class std::allocator<char>>::str(void)const"),
("?str@?$basic_stringbuf@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEXABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z", "public: void __thiscall std::basic_stringbuf<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("?str@?$basic_stringbuf@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBE?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@XZ", "public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> __thiscall std::basic_stringbuf<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(void)const"),
("?str@?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z", "public: void __thiscall std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> const &)"),
("?str@?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ", "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>> __thiscall std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char>>::str(void)const"),
("?str@?$basic_stringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QAEXABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@@Z", "public: void __thiscall std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> const &)"),
("?str@?$basic_stringstream@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@QBE?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@2@XZ", "public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>> __thiscall std::basic_stringstream<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short>>::str(void)const"),
("?_Sync@ios_base@std@@0_NA", "private: static bool std::ios_base::_Sync"),
("??_U@YAPAXI@Z", "void * __cdecl operator new[](unsigned int)"),
("??_V@YAXPAX@Z", "void __cdecl operator delete[](void *)"),
("??X?$_Complex_base@M@std@@QAEAAV01@ABM@Z", "public: class std::_Complex_base<float> & __thiscall std::_Complex_base<float>::operator*=(float const &)"),
("??Xstd@@YAAAV?$complex@M@0@AAV10@ABV10@@Z", "class std::complex<float> & __cdecl std::operator*=(class std::complex<float> &,class std::complex<float> const &)"),
("?aaa@@YAHAAUbbb@@@Z", "int __cdecl aaa(struct bbb &)"),
("?aaa@@YAHBAUbbb@@@Z", "int __cdecl aaa(struct bbb & volatile)"),
("?aaa@@YAHPAUbbb@@@Z", "int __cdecl aaa(struct bbb *)"),
("?aaa@@YAHQAUbbb@@@Z", "int __cdecl aaa(struct bbb * const)"),
("?aaa@@YAHRAUbbb@@@Z", "int __cdecl aaa(struct bbb * volatile)"),
("?aaa@@YAHSAUbbb@@@Z", "int __cdecl aaa(struct bbb * const volatile)"),
("??0aa.a@@QAE@XZ", "public: __thiscall aa.a::aa.a(void)"), # INVALID, '.' should not be allowed in a name fragment
("??0aa$_3a@@QAE@XZ", "public: __thiscall aa$_3a::aa$_3a(void)"),
("??2?$aaa@AAUbbb@@AAUccc@@AAU2@@ddd@1eee@2@QAEHXZ", "public: int __thiscall eee::eee::ddd::ddd::aaa<struct bbb &,struct ccc &,struct ccc &>::operator new(void)"),
("?pSW@@3P6GHKPAX0PAU_tagSTACKFRAME@@0P6GH0K0KPAK@ZP6GPAX0K@ZP6GK0K@ZP6GK00PAU_tagADDRESS@@@Z@ZA", "int (__stdcall * pSW)(unsigned long,void *,void *,struct _tagSTACKFRAME *,void *,int (__stdcall *)(void *,unsigned long,void *,unsigned long,unsigned long *),void * (__stdcall *)(void *,unsigned long),unsigned long (__stdcall *)(void *,unsigned long),unsigned long (__stdcall *)(void *,void *,struct _tagADDRESS *))"),
("?$_aaa@Vbbb@@", "_aaa<class bbb>"),
("?$aaa@Vbbb@ccc@@Vddd@2@", "aaa<class ccc::bbb,class ccc::ddd>"),
("??0?$Foo@P6GHPAX0@Z@@QAE@PAD@Z", "public: __thiscall Foo<int (__stdcall *)(void *,void *)>::Foo<int (__stdcall *)(void *,void *)>(char *)"),
("??0?$Foo@P6GHPAX0@Z@@QAE@PAD@Z", "public: __thiscall Foo<int (__stdcall *)(void *,void *)>::Foo<int (__stdcall *)(void *,void *)>(char *)"),
("?Qux@Bar@@0PAP6AHPAV1@AAH1PAH@ZA", "private: static int (__cdecl * * Bar::Qux)(class Bar *,int &,int &,int *)"),
("?Qux@Bar@@0PAP6AHPAV1@AAH1PAH@ZA", "private: static int (__cdecl * * Bar::Qux)(class Bar *,int &,int &,int *)"),
("?$AAA@$DBAB@", "AAA<`template-parameter257'>"),
("?$AAA@?C@", "AAA<`template-parameter-2'>"),
("?$AAA@PAUBBB@@", "AAA<struct BBB *>"),
("??$ccccc@PAVaaa@@@bar@bb@foo@@DGPAV0@PAV0@PAVee@@IPAPAVaaa@@1@Z", "private: static class bar * __stdcall foo::bb::bar::ccccc<class aaa *>(class bar *,class ee *,unsigned int,class aaa * *,class ee *)"),
("?f@T@@QAEHQCY1BE@BO@D@Z", "public: int __thiscall T::f(char ( volatile * const)[20][30])"),
("?f@T@@QAEHQAY2BE@BO@CI@D@Z", "public: int __thiscall T::f(char ( * const)[20][30][40])"),
("?f@T@@QAEHQAY1BE@BO@$$CBD@Z", "public: int __thiscall T::f(char const ( * const)[20][30])"),
("??0?$Foo@U?$vector_c@H$00$01$0?1$0A@$0A@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@$0HPPPPPPP@@mpl@boost@@@@QAE@XZ", "public: __thiscall Foo<struct boost::mpl::vector_c<int,1,2,-2,0,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647>>::Foo<struct boost::mpl::vector_c<int,1,2,-2,0,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647>>(void)"),
("?swprintf@@YAHPAGIPBGZZ", "int __cdecl swprintf(unsigned short *,unsigned int,unsigned short const *,...)"),
("?vswprintf@@YAHPAGIPBGPAD@Z", "int __cdecl vswprintf(unsigned short *,unsigned int,unsigned short const *,char *)"),
("?vswprintf@@YAHPA_WIPB_WPAD@Z", "int __cdecl vswprintf(wchar_t *,unsigned int,wchar_t const *,char *)"),
("?swprintf@@YAHPA_WIPB_WZZ", "int __cdecl swprintf(wchar_t *,unsigned int,wchar_t const *,...)"),
("??Xstd@@YAAEAV?$complex@M@0@AEAV10@AEBV10@@Z", "class std::complex<float> & __ptr64 __cdecl std::operator*=(class std::complex<float> & __ptr64,class std::complex<float> const & __ptr64)"),
("?_Doraise@bad_cast@std@@MEBAXXZ", "protected: virtual void __cdecl std::bad_cast::_Doraise(void)const __ptr64"),
("??$?DM@std@@YA?AV?$complex@M@0@ABMABV10@@Z", "class std::complex<float> __cdecl std::operator*<float>(float const &,class std::complex<float> const &)"),
("?_R2@?BN@???$_Fabs@N@std@@YANAEBV?$complex@N@1@PEAH@Z@4NB", "double const `double __cdecl std::_Fabs<double>(class std::complex<double> const & __ptr64,int * __ptr64)'::`29'::_R2"),
("?vtordisp_thunk@std@@$4PPPPPPPM@3EAA_NXZ", "[thunk]:public: virtual bool __cdecl std::vtordisp_thunk`vtordisp{4294967292,4}' (void) __ptr64"),
("??_9CView@@$BBII@AE", "[thunk]: __thiscall CView::`vcall'{392,{flat}}' }'"),
("?_dispatch@_impl_Engine@SalomeApp@@$R4CE@BA@PPPPPPPM@7AE_NAAVomniCallHandle@@@Z", "[thunk]:public: virtual bool __thiscall SalomeApp::_impl_Engine::_dispatch`vtordispex{36,16,4294967292,8}' (class omniCallHandle &)"),
("?_Doraise@bad_cast@std@@MEBAXXZ", "protected: virtual void __cdecl std::bad_cast::_Doraise(void)const __ptr64"),
("??Xstd@@YAAEAV?$complex@M@0@AEAV10@AEBV10@@Z", "class std::complex<float> & __ptr64 __cdecl std::operator*=(class std::complex<float> & __ptr64,class std::complex<float> const & __ptr64)"),
("??Xstd@@YAAEAV?$complex@M@0@AEAV10@AEBV10@@Z", "class std::complex<float> & __ptr64 __cdecl std::operator*=(class std::complex<float> & __ptr64,class std::complex<float> const & __ptr64)"),
("??$run@XVTask_Render_Preview@@@QtConcurrent@@YA?AV?$QFuture@X@@PEAVTask_Render_Preview@@P82@EAAXXZ@Z", "class QFuture<void> __cdecl QtConcurrent::run<void,class Task_Render_Preview>(class Task_Render_Preview * __ptr64,void (__cdecl Task_Render_Preview::*)(void) __ptr64)"),
("??_E?$TStrArray@$$BY0BAA@D$0BA@@@UAEPAXI@Z", "public: virtual void * __thiscall TStrArray<char [256],16>::`vector deleting destructor'(unsigned int)"),

# Some other tests
("NotMangled", "NotMangled"),
("?variable@@4HA", "int variable"),
("?variable@@3HA", "int variable"),
("?variable@@2HA", "public: static int variable"),
("?variable@@1HA", "protected: static int variable"),
("?variable@@0HA", "private: static int variable"),
("?variable@@4JA", "long variable"),
("?variable@@4JB", "long const variable"),
("?a@@YE@V0@@Z", " __thiscall a(class a)"),
("?a@@YE@Vx@@@Z", " __thiscall a(class x)"),
("?a@@YE@Vx@0@@Z", " __thiscall a(class a::x)"),
("?a@@YE@V0@H@Z", " __thiscall a(class a,int)"),
("?a@@YE@W40@@Z", " __thiscall a(enum a)"),
("?a@@YE@W4x@@@Z", " __thiscall a(enum x)"),
("?a@@YE@W4x@0@@Z", " __thiscall a(enum a::x)"),
("?a@@YE@W40@H@Z", " __thiscall a(enum a,int)"),
("?d@@YAHPAH@Z", "int __cdecl d(int *)"),
("?d@@YAHQAH@Z", "int __cdecl d(int * const)"),
("?d@@YAHAAPAH@Z", "int __cdecl d(int * &)"),
("?a@@UAAXXZ", "public: virtual void __cdecl a(void)"),
("?a@@UAA@XZ", "public: virtual __cdecl a(void)"),
("?a@@UAAXH@Z", "public: virtual void __cdecl a(int)"),
("??0a@@QEAA@XZ", "public: __cdecl a::a(void) __ptr64"),
("??0a@@IEAA@XZ", "protected: __cdecl a::a(void) __ptr64"),
("??1a@@UEAA@XZ", "public: virtual __cdecl a::~a(void) __ptr64"),
("?a@@AEBE@QEAH@Z", "private: __thiscall a(int * __ptr64 const)const __ptr64"),
("?a@@AEBE@QEBH@Z", "private: __thiscall a(int const * __ptr64 const)const __ptr64"),
("?a@b@@QAAHXZ", "public: int __cdecl b::a(void)"),
("?a@b@@SAPAHXZ", "public: static int * __cdecl b::a(void)"),
("?a@b@@SAPAVc@@XZ", "public: static class c * __cdecl b::a(void)"),
("?a@b@@SAV1@XZ", "public: static class b __cdecl b::a(void)"),
("?a@b@@SAPAV1@XZ", "public: static class b * __cdecl b::a(void)"),
("?a@b@@SAV1c@@XZ", "public: static class c::b __cdecl b::a(void)"),
("?a@b@@YAXPBD@Z", "void __cdecl b::a(char const *)"),
("?a@b@@AAEXH@Z", "private: void __thiscall b::a(int)"),
("?a@b@@UEAAEK@Z", "public: virtual unsigned char __cdecl b::a(unsigned long) __ptr64"),
("?a@b@@QEAAEKK@Z", "public: unsigned char __cdecl b::a(unsigned long,unsigned long) __ptr64"),
("?a@b@@UEAAEPEBGZZ", "public: virtual unsigned char __cdecl b::a(unsigned short const * __ptr64,...) __ptr64"),
("?UnlockBuffer@?$def@H@@QAAXXZ", "public: void __cdecl def<int>::UnlockBuffer(void)"),
("?SPrintfAppend@DSTRING@@UAAEPBGZZ", "public: virtual unsigned char __cdecl DSTRING::SPrintfAppend(unsigned short const *,...)"),
("?SPrintf@DSTRING@@UAAEPBGZZ", "public: virtual unsigned char __cdecl DSTRING::SPrintf(unsigned short const *,...)"),
("?_Mutex@std@@YCVtoto@@XZ", "class toto __pascal std::_Mutex(void)"),
("??0?$CStringT@GV?$StrTraitATL@GV?$ChTraitsCRT@G@ATL@@@ATL@@@ATL@@QAA@XZ", "public: __cdecl ATL::CStringT<unsigned short,class ATL::StrTraitATL<unsigned short,class ATL::ChTraitsCRT<unsigned short>>>::CStringT<unsigned short,class ATL::StrTraitATL<unsigned short,class ATL::ChTraitsCRT<unsigned short>>>(void)"),
("?a@b@c@d@@SAV1toto@@XZ", "public: static class toto::b __cdecl d::c::b::a(void)"),
("?a@b@@UEBAJPEBV1@@Z", "public: virtual long __cdecl b::a(class b const * __ptr64)const __ptr64"),
("?a@b@c@d@@QAE@W4e@1@@Z", "public: __thiscall d::c::b::a(enum b::e)"),
("??0a@b@c@d@@QAE@W4e@1@@Z", "public: __thiscall d::c::b::a::a(enum b::e)"),
("??2a@b@c@d@@QAE@W4e@1@@Z", "public: __thiscall d::c::b::a::operator new(enum b::e)"),
("?a@b@@QEAAEPEBGK@Z", "public: unsigned char __cdecl b::a(unsigned short const * __ptr64,unsigned long) __ptr64"),
("?a@b@@QEAAEPEBV1@KK@Z", "public: unsigned char __cdecl b::a(class b const * __ptr64,unsigned long,unsigned long) __ptr64"),
("?a@b@@QEAAEPEBV1@@Z", "public: unsigned char __cdecl b::a(class b const * __ptr64) __ptr64"),
("??0?$a@G$0A@@b@@QAA@ABV01@@Z", "public: __cdecl b::a<unsigned short,0>::a<unsigned short,0>(class b::a<unsigned short,0> const &)"),
("?desc@@QAA@P6APAVroot@@PAVpage@@@Z@Z", "public: __cdecl desc(class root * (__cdecl *)(class page *))"),
("?d@@YAHAAQAH@Z", "int __cdecl d(int * &)"),
("?c@@YA?AV?$b@X@@H@Z", "class b<void> __cdecl c(int)"),
("?a@b@@QIAEHXZ", "public: int __thiscall b::a(void) __restrict"),
("?a@@QAEH$$QAVb@@@Z", "public: int __thiscall a(class b &&)"),
("?a@@QAEH$$RAVb@@@Z", "public: int __thiscall a(class b && volatile)"),
("?a@@QAEH$$CAVb@@@Z", "public: int __thiscall a(class b)"),
("?a@b@@AAEH_OB_OCFHH@Z", "private: int __thiscall b::a(short const [][],int,int)"),
("?a@@3V?$b@HVc@@@@A", "class b<int,class c> a"),
("??0a@b@@QEAA@PEAVc@1@P821@EAAPEAVd@1@PEAV31@1PEAVe@f@@@ZPEAVg@5@@Z", "public: __cdecl b::a::a(class b::c * __ptr64,class b::d * __ptr64 (__cdecl b::c::*)(class b::d * __ptr64,class b::d * __ptr64,class f::e * __ptr64) __ptr64,class f::g * __ptr64) __ptr64"),
("??_Da@@QEAAXXZ", "public: void __cdecl a::`vbase destructor'(void) __ptr64"),
("??_Fa@@QEAAXXZ", "public: void __cdecl a::`default constructor closure'(void) __ptr64"),

# For code coverage
("?Invalid@@x", "?Invalid@@x"),
("?$Invalid@$0x@", "?$Invalid@$0x@"),
("?Invalid@@$$FYMHP$DFCH@Z", "?Invalid@@$$FYMHP$DFCH@Z"),

# Calling conventions
("?a@@YAHF@Z", "int __cdecl a(short)"),
("?a@@YBHF@Z", "int __cdecl __dll_export a(short)"),
("?a@@YCHF@Z", "int __pascal a(short)"),
("?a@@YDHF@Z", "int __pascal __dll_export a(short)"),
("?a@@YEHF@Z", "int __thiscall a(short)"),
("?a@@YFHF@Z", "int __thiscall __dll_export a(short)"),
("?a@@YGHF@Z", "int __stdcall a(short)"),
("?a@@YHHF@Z", "int __stdcall __dll_export a(short)"),
("?a@@YIHF@Z", "int __fastcall a(short)"),
("?a@@YJHF@Z", "int __fastcall __dll_export a(short)"),
("?a@@YKHF@Z", "int a(short)"),
("?a@@YLHF@Z", "int __dll_export a(short)"),
("?a@@YMHF@Z", "int __clrcall a(short)"),
("?a@@YNHF@Z", "int __clrcall __dll_export a(short)"),
("?a@@YOHF@Z", "int __eabi a(short)"),
("?a@@YPHF@Z", "int __eabi __dll_export a(short)"),
("?a@@YQHF@Z", "int __vectorcall a(short)"),

# Data types
("?a@@YK_$MXZ", "__w64 float a(void)"),
("?a@@YKX_$M@Z", "void a(__w64 float)"),
("?a@@YK_$PAHXZ", "__w64 int * a(void)"),
("?a@@YKP6AXJ@ZXZ", "void (__cdecl * a(void))(long)"),
("?a@@YKQ6AXJ@ZXZ", "void (__cdecl * const a(void))(long)"),
("?a@@YKXP6AXJ@Z@Z", "void a(void (__cdecl *)(long))"),
("?a@@YK_$P6AXJ@ZXZ", "__w64 void (__cdecl * a(void))(long)"),
("?a@@YK?AHP80@AAXXZ@Z", "int a(void (__cdecl a::*)(void))"),
("?a@@YK?AHP8b@c@@AAXXZ@Z", "int a(void (__cdecl c::b::*)(void))"),
("?a@@YK?AHP8b@@BAXXZ@Z", "int a(void (__cdecl b::*)(void)const)"),
("?a@@YKX_OA_OAF@Z", "void a(short [][])"),
("?a@@YKX_OA_OAPAH@Z", "void a(int * [][])"),
("?a@@YKX_OA_OAP6AXJ@Z@Z", "void a(void (__cdecl *)(long) [][])"),

# Nested, with backreferences
("?a@??f@@YAXXZ@4HA", "int `void __cdecl f(void)'::a"),
("?a@b@??f@0@YAXXZ@4HA", "int `void __cdecl a::f(void)'::b::a"),

# Numbered/anonymous namespaces
("?a@?@@YEHF@Z", "int __thiscall `0'::a(short)"),
("?a@?BN@@YEHF@Z", "int __thiscall `29'::a(short)"),
("?a@?A@@YEHF@Z", "int __thiscall `anonymous namespace'::a(short)"),
("?a@?AN@@YEHF@Z", "int __thiscall `anonymous namespace'::a(short)"),

# Local static guard
("??_B@58", "`local static guard'{9}'"),
("??_B??a@@SAHXZ@51", "`public: static int __cdecl a(void)'::`local static guard'{2}'"),
("??_B?1??a@@SAHXZ@51", "`public: static int __cdecl a(void)'::`2'::`local static guard'{2}'"),
("??_B?1??a@b@c@@SAAEAVd@2@XZ@51", "`public: static class c::d & __ptr64 __cdecl c::b::a(void)'::`2'::`local static guard'{2}'"),

# RTTI
("??_R0PADa@@AAE@H@Z", "private: __thiscall a::char * `RTTI Type Descriptor'(int)"),
("??_R13433a@@AAE@H@Z", "private: __thiscall a::`RTTI Base Class Descriptor at (4,5,4,4)'(int)"),
("??_R2a@@AAE@H@Z", "private: __thiscall a::`RTTI Base Class Array'(int)"),
("??_R4a@@AAE@H@Z", "private: __thiscall a::`RTTI Complete Object Locator'(int)"),
("??_R3a@@AAE@H@Z", "private: __thiscall a::`RTTI Class Hierarchy Descriptor'(int)"),

# Some other special fragments
("??Ba@@QAAAAVb@@XZ", "public: __cdecl a::operator class b &(void)"),
("??_Car@@AAE@H@Z", "`string'"),
("??__Ea@@AAEXH@Z", "private: void __thiscall `dynamic initializer for 'a''(int)"),
("??__Fa@@AAEXH@Z", "private: void __thiscall `dynamic atexit destructor for 'a''(int)"),
("??__Ka@@AAEXH@Z", 'private: void __thiscall operator "" a(int)'),
("??_Va@@YAXPAXV0@@Z", "void __cdecl a::operator delete[](void *,class a)"),
("??_7a@@6B@", "const a::`vftable'"),
("??_8a@@6Bx@@@", "const a::`vbtable'{for `x'}"),
("??_PAa@@AAE@H@Z", "private: __thiscall a::`udt returning'operator[](int)"),
("??_P_R4a@0@AAE@H@Z", "private: __thiscall a::a::`udt returning'`RTTI Complete Object Locator'(int)"),

# CV:
("?@?a@@YAHF@Z", "CV: int __cdecl a(short)"),
("?@?a@@4HA", "CV: int a"),

# template parameters
("?$a@?C@", "a<`template-parameter-2'>"),
("?$a@$DBAB@", "a<`template-parameter257'>"), # not known by undname.exe
("?$a@$0A@", "a<0>"),
("?a@@3U?$b@$09@@A", "struct b<10> a"),
("?a@@3U?$b@$1?c@@3HA@@A", "struct b<&int c> a"),
("?a@@3U?$b@$1?c@@3PADA@@A", "struct b<&char * c> a"),
# meaningless results
("?$a@$22C@", "a<3.e2>"),
("?$a@$29C@", "a<1.0e2>"),
("?$a@$F1CD@", "a<{2,35}>"),
("?$a@$G0CD@B@", "a<{1,35,1}>"),

# vtordisp
("?a@@$023AAHXZ", "[thunk]:private: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$123AAHXZ", "[thunk]:private: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$223AAHXZ", "[thunk]:protected: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$323AAHXZ", "[thunk]:protected: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$423AAHXZ", "[thunk]:public: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$523AAHXZ", "[thunk]:public: virtual int __cdecl a`vtordisp{3,4}' (void)"),
("?a@@$R42345AAHXZ", "[thunk]:public: virtual int __cdecl a`vtordispex{3,4,5,6}' (void)"),

# C++/CLI
("?a@@$$FQ$AAMXXZ", "[managed] public: void __clrcall a(void)"),
("?a@@$$FQ$CAMXXZ", "[managed] public: void __clrcall a(void)%"),
("?a@@$$FYMHP$AA__ZVb@@@Z", "[managed] int __clrcall a(class b ^)"),
("?a@@YMHP$03AH@Z", "int __clrcall a(cli::array<int ,3>^)"),
("?a@@$$FYMHP$03AH@Z", "[managed] int __clrcall a(cli::array<int ,3>^)"),
("__mep@?a@@$$FQ$AAMXXZ", "[MEP] [managed] public: void __clrcall a(void)"),
("?a@@$$HYMHP$01AP$AAVb@@@Z", "[MANAGED] int __clrcall a(cli::array<class b ^ >^)"),
("?a@@$$FYMP$AAHXZ", "[managed] int ^ __clrcall a(void)"),
("?a@@$$FYMA$AAHXZ", "[managed] int % __clrcall a(void)"),
# these inputs may be invalid, they were not generated by VC++
("?a@@$$FYMHP$AEBH@Z", "[managed] int __clrcall a(int const ^ __ptr64)"),
("?a@@$$FYMHP$BECH@Z", "[managed] int __clrcall a(cli::pin_ptr<int volatile * __ptr64)"),
("?a@@$$FYMHA$BECH@Z", "[managed] int __clrcall a(cli::pin_ptr<int volatile & __ptr64)"),
("?a@@$$FYMHP$CEBH@Z", "[managed] int __clrcall a(int const % __ptr64)"),
("?a@@$$FYMHP$01WH@Z", "[managed] int __clrcall a(cli::array<int >^)"), # 'W' seems ignored
("?a@@$$FYMHP$AEBP6AXJ@Z@Z", "[managed] int __clrcall a(void (__cdecl * const ^ __ptr64)(long))"),
("?a@@$$FYMHP$BECP6AXJ@Z@Z", "[managed] int __clrcall a(cli::pin_ptr<void (__cdecl * volatile * __ptr64)(long))"),

# __based
("?a@@3PM2b@@HM21@", "int __based(b) * __based(b) a"),
("?a@@YAPM2b@@HF@Z", "int __based(b) * __cdecl a(short)"),
("?a@@YAQM2b@@HF@Z", "int __based(b) * const __cdecl a(short)"),
("?a@@YAPM2b@@HPM21@H@Z", "int __based(b) * __cdecl a(int __based(b) *)"),
("?a@@YAPM2b@@HQM21@H@Z", "int __based(b) * __cdecl a(int __based(b) * const)"),

# throw
("?a@@YKFH@HH@", "short a(int) throw(int,int)"),
("?_CxxThrowException@@$$J18YGXPAXPBU_s__ThrowInfo@@@Z", 'extern "C" void __stdcall _CxxThrowException(void *,struct _s__ThrowInfo const *)'),
]

from test_all import run_tests, assertion
from elfesteem.visual_studio_mangling import symbol_demangle

def test_mangling(assertion):
    for k, v in tests:
        n, r = symbol_demangle(k)
        if r or (v != n):
            assertion(0,1, k)

def run_test(assertion):
    return test_mangling(assertion)

if __name__ == "__main__":
    run_tests(run_test)
